### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by Roughtrade** [archphile/mpd-manisiutkin#1]
Compiling on a Raspberry Pi / Debian strech

mv -f src/neighbor/plugins/.deps/libneighbor_a-UpnpNeighborPlugin.Tpo src/neighbor/plugins/.deps/libneighbor_a-UpnpNeighborPlugin.Po
g++ -DHAVE_CONFIG_H -I.  -DNDEBUG -I./src -I/usr/include -DSYSTEM_CONFIG_FILE_LOCATION='"/usr/local/etc/mpd.conf"' -I/usr/include/dbus-1.0 -I/usr/lib/arm-linux-gnueabihf/dbus-1.0/include -pthread -I/usr/include/upnp  -D_GNU_SOURCE -pthread -g -O2 -fvisibility=hidden -fno-threadsafe-statics -fmerge-all-constants -ffast-math -ftree-vectorize -ffunction-sections -fdata-sections -Wall -Wextra -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wwrite-strings -Wsign-compare -Wno-noexcept-type -MT src/neighbor/plugins/libneighbor_a-UdisksNeighborPlugin.o -MD -MP -MF src/neighbor/plugins/.deps/libneighbor_a-UdisksNeighborPlugin.Tpo -c -o src/neighbor/plugins/libneighbor_a-UdisksNeighborPlugin.o `test -f 'src/neighbor/plugins/UdisksNeighborPlugin.cxx' || echo './'`src/neighbor/plugins/UdisksNeighborPlugin.cxx
src/neighbor/plugins/UdisksNeighborPlugin.cxx: In instantiation of ‘UdisksNeighborExplorer::HandleMessage(DBusConnection*, DBusMessage*)::<lambda(const char*, auto:4&&)> [with auto:4 = ODBus::ReadMessageIter]’:
./src/lib/dbus/ObjectManager.hxx:59:3:   required from ‘void ODBus::RecurseInterfaceDictEntry(ODBus::ReadMessageIter&&, F&&) [with F = UdisksNeighborExplorer::HandleMessage(DBusConnection*, DBusMessage*)::<lambda(const char*, auto:4&&)>]’
src/neighbor/plugins/UdisksNeighborPlugin.cxx:240:5:   required from here
src/neighbor/plugins/UdisksNeighborPlugin.cxx:235:89: warning: declaration of ‘ODBus::ReadMessageIter&& i’ shadows a parameter [-Wshadow]
   RecurseInterfaceDictEntry(ReadMessageIter(*message), [this](const char *path, auto &&i){
                                                                                         ^
In file included from src/neighbor/plugins/UdisksNeighborPlugin.cxx:28:0:
./src/lib/dbus/ObjectManager.hxx:49:45: note: shadowed declaration is here
 RecurseInterfaceDictEntry(ReadMessageIter &&i, F &&f)
                                             ^
src/neighbor/plugins/UdisksNeighborPlugin.cxx:235:89: warning: declaration of ‘path’ shadows a previous local [-Wshadow]
   RecurseInterfaceDictEntry(ReadMessageIter(*message), [this](const char *path, auto &&i){
                                                                                         ^
In file included from src/neighbor/plugins/UdisksNeighborPlugin.cxx:28:0:
./src/lib/dbus/ObjectManager.hxx:54:14: note: shadowed declaration is here
  const char *path = i.GetString();
              ^~~~
src/neighbor/plugins/UdisksNeighborPlugin.cxx:239:12: error: cannot call member function ‘void UdisksNeighborExplorer::Insert(UDisks2::Object&&)’ without object
      Insert(std::move(o));
      ~~~~~~^~~~~~~~~~~~~~
cc1plus: warning: unrecognized command line option ‘-Wno-noexcept-type’
Makefile:14455: die Regel für Ziel „src/neighbor/plugins/libneighbor_a-UdisksNeighborPlugin.o“ scheiterte
make[1]: *** [src/neighbor/plugins/libneighbor_a-UdisksNeighborPlugin.o] Fehler 1
make[1]: Verzeichnis „/home/pi/mpd-manisiutkin“ wird verlassen
Makefile:5274: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2


Any Idea for me ?

Regards Peter

**Comment by archphile** [comment]
I am sorry, 

The purpose of this repository is to just keep a copy of the code of the original repo:

https://sourceforge.net/p/sacddecoder/mpd/MPD.git/ci/master/tree/

Regards,

M.
