### ISSUE TITLE
compile program

### ISSUE THREAD

**Issue by pisteps** [archphile/mpd-manisiutkin#2]
hello,
i'd like to compile this version of mpd to use with my OS (libreelec for a raspberry pi3).
are there any dependences that i should add when i build the program compared to mpd 0.20.19?
standard mpd uses these dependences:
PKG_DEPENDS_TARGET="toolchain boost glib ffmpeg libmad libogg flac faad2 curl alsa-lib yajl libid3tag lame"

thanks a lot

**Comment by archphile** [comment]
Hi,

You can check my PKGBUILD here to see how I build it:

https://github.com/archphile/playground/blob/master/mpd-archphile-sacd/PKGBUILD

Please note that the source on my repo, was taken from:

https://sourceforge.net/p/sacddecoder/mpd/MPD.git/ci/master/tree/

**Comment by pisteps** [comment]
not sure if you can help, but  i try anyway...
as i said above i am building this version of mpd to use with libreelec for a raspberry pi3.
i am having problems with one of the dependences, libmpdclient.
the building/compiling process stops with this error:
```
UNPACK libmpdclient
BUILD libmpdclient (target)
Executing (target): make
make: *** No targets specified and no makefile found. Stop.
```
tried libmpdclient 2.13 and 2.14 but same results.
any advice?
