### ISSUE TITLE
failed to compile in ARCHLINUX

### ISSUE THREAD

**Issue by speeedturtle** [archphile/mpd-manisiutkin#4]
roon@apl ~/Music/mpd-manisiutkin (git)-[master] % meson . output/release --buildtype=debugoptimized -Db_ndebug=true
The Meson build system
Version: 0.54.2
Source dir: /home/roon/Music/mpd-manisiutkin
Build dir: /home/roon/Music/mpd-manisiutkin/output/release
Build type: native build
Project name: mpd
Project version: 0.22~git
C compiler for the host machine: cc (gcc 10.1.0 "cc (GCC) 10.1.0")
C linker for the host machine: cc ld.bfd 2.34.0
C++ compiler for the host machine: c++ (gcc 10.1.0 "c++ (GCC) 10.1.0")
C++ linker for the host machine: c++ ld.bfd 2.34.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found git repository at /home/roon/Music/mpd-manisiutkin
Compiler for C++ supports arguments -Wall: YES 
Compiler for C++ supports arguments -Wextra: YES 
Compiler for C++ supports arguments -Wvla: YES 
Compiler for C++ supports arguments -fvisibility=hidden: YES 
Compiler for C++ supports arguments -ffast-math: YES 
Compiler for C++ supports arguments -ftree-vectorize: YES 
Compiler for C++ supports arguments -fno-threadsafe-statics: YES 
Compiler for C++ supports arguments -fmerge-all-constants: YES 
Compiler for C++ supports arguments -Wmissing-declarations: YES 
Compiler for C++ supports arguments -Wshadow: YES 
Compiler for C++ supports arguments -Wpointer-arith: YES 
Compiler for C++ supports arguments -Wcast-qual: YES 
Compiler for C++ supports arguments -Wwrite-strings: YES 
Compiler for C++ supports arguments -Wsign-compare: YES 
Compiler for C++ supports arguments -Wno-non-virtual-dtor -Wnon-virtual-dtor: YES 
Compiler for C++ supports arguments -Wno-noexcept-type -Wnoexcept-type: YES 
Compiler for C++ supports arguments -ffunction-sections: YES 
Compiler for C++ supports arguments -fdata-sections: YES 
meson.build:106: WARNING: Consider using the built-in warning_level option instead of using "-Wall".
meson.build:106: WARNING: Consider using the built-in warning_level option instead of using "-Wextra".
Compiler for C supports arguments -Wall: YES 
Compiler for C supports arguments -Wextra: YES 
Compiler for C supports arguments -Wvla: YES 
Compiler for C supports arguments -fvisibility=hidden: YES 
Compiler for C supports arguments -ffast-math: YES 
Compiler for C supports arguments -ftree-vectorize: YES 
Compiler for C supports arguments -Wmissing-prototypes: YES 
Compiler for C supports arguments -Wshadow: YES 
Compiler for C supports arguments -Wpointer-arith: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wcast-qual: YES 
Compiler for C supports arguments -Wwrite-strings: YES 
Compiler for C supports arguments -pedantic: YES 
Compiler for C supports arguments -ffunction-sections: YES 
Compiler for C supports arguments -fdata-sections: YES 
meson.build:107: WARNING: Consider using the built-in warning_level option instead of using "-Wall".
meson.build:107: WARNING: Consider using the built-in warning_level option instead of using "-Wextra".
Compiler for C++ supports link arguments -Wl,--gc-sections: YES 
Has header "locale.h" : YES 
Checking for function "getpwnam_r" : YES 
Checking for function "getpwuid_r" : YES 
Checking for function "initgroups" : YES 
Checking for function "fnmatch" : YES 
Checking for function "strndup" : YES 
Checking for function "strcasestr" : YES 
Checking for function "syslog" : YES 
Run-time dependency Boost found: YES 1.72.0 (/usr)
Run-time dependency threads found: YES
Checking for function "pthread_setname_np" with dependency threads: YES 
Found pkg-config: /bin/pkg-config (1.6.3)
Run-time dependency dbus-1 found: YES 1.12.16
Run-time dependency icu-i18n found: YES 67.1
Run-time dependency smbclient found: YES 0.6.0
Run-time dependency zlib found: YES 1.2.11
Run-time dependency alsa found: YES 1.2.2
Run-time dependency libchromaprint found: YES 1.5.0
Run-time dependency libcurl found: YES 7.70.0
Run-time dependency expat found: YES 2.2.9
Run-time dependency libavformat found: YES 58.29.100
Run-time dependency libavcodec found: YES 58.54.100
Run-time dependency libavutil found: YES 56.31.100
Run-time dependency libavfilter found: YES 7.57.100
Run-time dependency libnfs found: YES 4.0.0
Run-time dependency libpcre found: YES 8.44
Run-time dependency libpulse found: YES 13.0
Library sndio found: YES
Header <sndio.h> has symbol "ROAR_VERSION" : NO 
Run-time dependency sqlite3 found: YES 3.31.1
Run-time dependency libsystemd found: YES 245
Run-time dependency libupnp found: YES 1.6.25
Run-time dependency yajl found: YES 2.1.0
Header <sys/socket.h> has symbol "AF_INET6" : YES 
Header <sys/socket.h> has symbol "struct ucred" : YES 
Header <sys/socket.h> has symbol "SO_PEERCRED" : YES 
Checking for function "getpeereid" : NO 
Run-time dependency id3tag found: YES 0.15.1b
Run-time dependency samplerate found: YES 0.1.9
Run-time dependency soxr found: YES 0.1.3
Run-time dependency libcdio_paranoia found: YES 10.2+2.0.0
Run-time dependency libmms found: YES 0.6.4
Run-time dependency libiso9660 found: YES 2.1.0
Library bz2 found: YES
Run-time dependency zziplib found: YES 0.13.71
Run-time dependency ao found: YES 1.2.2
Run-time dependency jack found: YES 0.125.0
Header <jack/jack.h> has symbol "jack_set_info_function" : YES 
Run-time dependency openal found: YES 1.20.1
Run-time dependency shout found: YES 2.4.3
Run-time dependency flac found: YES 1.3.3
Run-time dependency opus found: YES 1.3.1
Run-time dependency vorbis found: YES 1.3.6
Run-time dependency vorbisenc found: YES 1.3.6
Run-time dependency ogg found: YES 1.3.4
Found CMake: /bin/cmake (3.17.2)
Run-time dependency adplug found: NO (tried pkgconfig and cmake)
Run-time dependency fluidsynth found: YES 2.1.2
Run-time dependency audiofile found: YES 0.3.6
Library faad found: YES
Library gme found: YES
Library mad found: YES
Run-time dependency libmikmod found: YES 3.3.11
Run-time dependency libmodplug found: YES 0.8.9.0
Library mpcdec found: YES
Run-time dependency libmpg123 found: YES 1.25.13
Run-time dependency sndfile found: YES 1.0.28
Run-time dependency wavpack found: YES 5.2.0
Library WildMidi found: YES
Run-time dependency libsidplayfp found: YES 2.0.2
Library mp3lame found: YES
Run-time dependency twolame found: YES 0.4.0
Run-time dependency shine found: NO (tried pkgconfig and cmake)
Run-time dependency avahi-client found: YES 0.8
Run-time dependency libmpdclient found: YES 2.18
Configuring config.h using configuration
Configuring mpd.service using configuration
Configuring mpd.service using configuration
Build targets in project: 70

Found ninja-1.10.0 at /bin/ninja
meson . output/release --buildtype=debugoptimized -Db_ndebug=true  8.32s user 3.55s system 99% cpu 11.949 total
roon@apl ~/Music/mpd-manisiutkin (git)-[master] % meson configure output/release
Core properties:
  Source dir /home/roon/Music/mpd-manisiutkin
  Build dir  /home/roon/Music/mpd-manisiutkin/output/release
                                                                                                       
Main project options:                                                                                  
                                                                                                       
  Core options            Current Value  Possible Values                                               Description
  ------------            -------------  ---------------                                               -----------
  auto_features           auto           [enabled, disabled, auto]                                     Override value of all 'auto' features
  backend                 ninja          [ninja, vs, vs2010, vs2015, vs2017, vs2019, xcode]            Backend to use
  buildtype               debugoptimized [plain, debug, debugoptimized, release, minsize, custom]      Build type to use
  debug                   true           [true, false]                                                 Debug
  default_library         shared         [shared, static, both]                                        Default library type
  install_umask           0022           [preserve, 0000-0777]                                         Default umask to apply on permissions of installed files
  layout                  mirror         [mirror, flat]                                                Build directory layout
  optimization            2              [0, g, 1, 2, 3, s]                                            Optimization level
  strip                   false          [true, false]                                                 Strip targets on install
  unity                   off            [on, off, subprojects]                                        Unity build
  unity_size              4              >=2                                                           Unity block size
  warning_level           1              [0, 1, 2, 3]                                                  Compiler warning level to use
  werror                  false          [true, false]                                                 Treat warnings as errors
  wrap_mode               default        [default, nofallback, nodownload, forcefallback]              Wrap mode
  cmake_prefix_path       []                                                                           List of additional prefixes for cmake to search
  pkg_config_path         []                                                                           List of additional paths for pkg-config to search
                                                                                                       
  Backend options         Current Value  Possible Values                                               Description
  ---------------         -------------  ---------------                                               -----------
  backend_max_links       0              >=0                                                           Maximum number of linker processes to run or 0 for no limit
                                                                                                       
  Base options            Current Value  Possible Values                                               Description
  ------------            -------------  ---------------                                               -----------
  b_asneeded              true           [true, false]                                                 Use -Wl,--as-needed when linking
  b_colorout              always         [auto, always, never]                                         Use colored output
  b_coverage              false          [true, false]                                                 Enable coverage tracking.
  b_lto                   false          [true, false]                                                 Use link time optimization
  b_lundef                true           [true, false]                                                 Use -Wl,--no-undefined when linking
  b_ndebug                true           [true, false, if-release]                                     Disable asserts
  b_pch                   true           [true, false]                                                 Use precompiled headers
  b_pgo                   off            [off, generate, use]                                          Use profile guided optimization
  b_pie                   false          [true, false]                                                 Build executables as position independent
  b_sanitize              none           [none, address, thread, undefined, memory, address,undefined] Code sanitizer to use
  b_staticpic             true           [true, false]                                                 Build static libraries as position independent
                                                                                                       
  Compiler options        Current Value  Possible Values                                               Description
  ----------------        -------------  ---------------                                               -----------
  c_args                  []                                                                           Extra arguments passed to the c compiler
  c_link_args             []                                                                           Extra arguments passed to the c linker
  c_std                   c99            [none, c89, c99, c11, c17, c18, gnu89, gnu99, gnu11, gnu17,   C language standard to use
                                          gnu18]                                                       
  cpp_args                []                                                                           Extra arguments passed to the cpp compiler
  cpp_debugstl            false          [true, false]                                                 STL debug mode
  cpp_eh                  default        [none, default, a, s, sc]                                     C++ exception handling type.
  cpp_link_args           []                                                                           Extra arguments passed to the cpp linker
  cpp_rtti                true           [true, false]                                                 Enable RTTI
  cpp_std                 c++17          [none, c++98, c++03, c++11, c++14, c++17, c++1z, c++2a,       C++ language standard to use
                                          gnu++03, gnu++11, gnu++14, gnu++17, gnu++1z, gnu++2a]        
                                                                                                       
  Directories             Current Value  Possible Values                                               Description
  -----------             -------------  ---------------                                               -----------
  bindir                  bin                                                                          Executable directory
  datadir                 share                                                                        Data file directory
  includedir              include                                                                      Header file directory
  infodir                 share/info                                                                   Info page directory
  libdir                  lib                                                                          Library directory
  libexecdir              libexec                                                                      Library executable directory
  localedir               share/locale                                                                 Locale data directory
  localstatedir           /var/local                                                                   Localstate data directory
  mandir                  share/man                                                                    Manual page directory
  prefix                  /usr/local                                                                   Installation prefix
  sbindir                 sbin                                                                         System executable directory
  sharedstatedir          /var/local/lib                                                               Architecture-independent data directory
  sysconfdir              etc                                                                          Sysconf data directory
                                                                                                       
  Testing options         Current Value  Possible Values                                               Description
  ---------------         -------------  ---------------                                               -----------
  errorlogs               true           [true, false]                                                 Whether to print the logs from failing tests
  stdsplit                true           [true, false]                                                 Split stdout and stderr in test logs
                                                                                                       
  Project options         Current Value  Possible Values                                               Description
  ---------------         -------------  ---------------                                               -----------
  adplug                  auto           [enabled, disabled, auto]                                     AdPlug decoder plugin
  alsa                    auto           [enabled, disabled, auto]                                     ALSA support
  android_abi             armeabi-v7a                                                                  The Android ABI to be built
  android_debug_keystore                                                                               The keystore file used to sign debug APK files
  android_keyalias                                                                                     The key alias used to sign APK files
  android_keypass                                                                                      The password of the keystore used to sign APK files
  android_keystore                                                                                     The keystore file used to sign APK files
  android_ndk                                                                                          The path where Android NDK is installed
  android_sdk                                                                                          The path where Android SDK is installed
  android_strip           strip                                                                        The "strip" tool from the NDK
  ao                      auto           [enabled, disabled, auto]                                     libao output plugin
  audiofile               auto           [enabled, disabled, auto]                                     libaudiofile decoder plugin
  bzip2                   auto           [enabled, disabled, auto]                                     bzip2 support using libbz2
  cdio_paranoia           auto           [enabled, disabled, auto]                                     libcdio_paranoia input plugin
  chromaprint             auto           [enabled, disabled, auto]                                     ChromaPrint / AcoustID support
  cue                     true           [true, false]                                                 CUE sheet support
  curl                    auto           [enabled, disabled, auto]                                     HTTP client using CURL
  daemon                  true           [true, false]                                                 enable daemonization
  database                true           [true, false]                                                 enable support for the music database
  dbus                    auto           [enabled, disabled, auto]                                     D-Bus support
  documentation           false          [true, false]                                                 Build documentation
  dsd                     true           [true, false]                                                 Support the DSD audio format
  dvdaiso                 true           [true, false]                                                 Support DVD-Audio ISO via libdvdaiso
  epoll                   true           [true, false]                                                 Use epoll on Linux
  eventfd                 true           [true, false]                                                 Use eventfd() on Linux
  expat                   auto           [enabled, disabled, auto]                                     Expat XML support
  faad                    auto           [enabled, disabled, auto]                                     AAC decoder using libfaad
  ffmpeg                  auto           [enabled, disabled, auto]                                     FFmpeg codec support
  fifo                    true           [true, false]                                                 FIFO output plugin
  flac                    auto           [enabled, disabled, auto]                                     FLAC decoder plugin
  fluidsynth              auto           [enabled, disabled, auto]                                     fluidsynth MIDI decoder plugin
  gme                     auto           [enabled, disabled, auto]                                     Game Music Emulator decoder plugin
  httpd                   true           [true, false]                                                 HTTP streaming output plugin
  iconv                   auto           [enabled, disabled, auto]                                     Use iconv() for character set conversion
  icu                     auto           [enabled, disabled, auto]                                     Use libicu for Unicode
  id3tag                  auto           [enabled, disabled, auto]                                     ID3 support using libid3tag
  inotify                 true           [true, false]                                                 inotify support (for automatic database update)
  ipv6                    auto           [enabled, disabled, auto]                                     Support for IPv6
  iso9660                 auto           [enabled, disabled, auto]                                     ISO9660 support using libiso9660
  jack                    auto           [enabled, disabled, auto]                                     JACK output plugin
  lame                    auto           [enabled, disabled, auto]                                     LAME MP3 encoder plugin
  libmpdclient            auto           [enabled, disabled, auto]                                     libmpdclient support (for the proxy database plugin)
  libsamplerate           auto           [enabled, disabled, auto]                                     libsamplerate resampler
  local_socket            true           [true, false]                                                 Support for clients connecting via local sockets
  mad                     auto           [enabled, disabled, auto]                                     MP3 decoder using libmad
  mikmod                  auto           [enabled, disabled, auto]                                     MikMod decoder plugin
  mms                     auto           [enabled, disabled, auto]                                     MMS protocol support using libmms
  modplug                 auto           [enabled, disabled, auto]                                     Modplug decoder plugin
  mpcdec                  auto           [enabled, disabled, auto]                                     Musepack decoder plugin
  mpg123                  auto           [enabled, disabled, auto]                                     MP3 decoder using libmpg123
  neighbor                true           [true, false]                                                 enable support for neighbor discovery
  nfs                     auto           [enabled, disabled, auto]                                     NFS protocol support using libnfs
  openal                  auto           [enabled, disabled, auto]                                     OpenAL output plugin
  opus                    auto           [enabled, disabled, auto]                                     Opus decoder plugin
  oss                     auto           [enabled, disabled, auto]                                     Open Sound System support
  pcre                    auto           [enabled, disabled, auto]                                     Enable regular expression support (using libpcre)
  pipe                    true           [true, false]                                                 Pipe output plugin
  pulse                   auto           [enabled, disabled, auto]                                     PulseAudio support
  qobuz                   auto           [enabled, disabled, auto]                                     Qobuz client
  recorder                true           [true, false]                                                 Recorder output plugin
  sacdiso                 true           [true, false]                                                 Support Super Audio CD ISO via libsacdiso
  shine                   auto           [enabled, disabled, auto]                                     shine MP3 encoder plugin
  shout                   auto           [enabled, disabled, auto]                                     Shoutcast streaming support using libshout
  sidplay                 auto           [enabled, disabled, auto]                                     C64 SID support via libsidplayfp or libsidplay2
  signalfd                true           [true, false]                                                 Use signalfd() on Linux
  smbclient               auto           [enabled, disabled, auto]                                     SMB support using libsmbclient
  sndfile                 auto           [enabled, disabled, auto]                                     libsndfile decoder plugin
  sndio                   auto           [enabled, disabled, auto]                                     sndio output plugin
  solaris_output          auto           [enabled, disabled, auto]                                     Solaris /dev/audio support
  soundcloud              auto           [enabled, disabled, auto]                                     SoundCloud client
  soxr                    auto           [enabled, disabled, auto]                                     libsoxr resampler
  sqlite                  auto           [enabled, disabled, auto]                                     SQLite database support (for stickers)
  syslog                  auto           [enabled, disabled, auto]                                     syslog support
  systemd                 auto           [enabled, disabled, auto]                                     systemd support
  systemd_system_unit_dir                                                                              systemd system service directory
  systemd_user_unit_dir                                                                                systemd user service directory
  tcp                     true           [true, false]                                                 Support for clients connecting via TCP
  test                    false          [true, false]                                                 Build the unit tests and debug programs
  tidal                   auto           [enabled, disabled, auto]                                     Tidal client
  tremor                  auto           [enabled, disabled, auto]                                     Fixed-point vorbis decoder plugin
  twolame                 auto           [enabled, disabled, auto]                                     TwoLAME MP2 encoder plugin
  udisks                  auto           [enabled, disabled, auto]                                     Support for removable media using udisks2
  upnp                    auto           [enabled, disabled, auto]                                     UPnP client support
  vorbis                  auto           [enabled, disabled, auto]                                     Vorbis decoder plugin
  vorbisenc               auto           [enabled, disabled, auto]                                     Vorbis encoder plugin
  wave_encoder            true           [true, false]                                                 PCM wave encoder encoder plugin
  wavpack                 auto           [enabled, disabled, auto]                                     WavPack decoder plugin
  webdav                  auto           [enabled, disabled, auto]                                     WebDAV support using CURL and Expat
  wildmidi                auto           [enabled, disabled, auto]                                     WildMidi decoder plugin
  yajl                    auto           [enabled, disabled, auto]                                     libyajl for YAML support
  zeroconf                auto           [auto, avahi, bonjour, disabled]                              Zeroconf support
  zlib                    auto           [enabled, disabled, auto]                                     zlib support (for database compression)
  zzip                    auto           [enabled, disabled, auto]                                     ZIP support using zziplib
roon@apl ~/Music/mpd-manisiutkin (git)-[master] % ninja -C output/release
ninja: Entering directory `output/release'
[2/693] Generating GitVersion.cxx with a custom command
fatal: No names found, cannot describe anything.
[11/693] Compiling C++ object 'src/util/ed6d25d@@util@sta/StringUtil.cxx.o'
FAILED: src/util/ed6d25d@@util@sta/StringUtil.cxx.o 
c++ -Isrc/util/ed6d25d@@util@sta -Isrc/util -I../../src/util -Isrc -I../../src -I. -I../.. -Isrc/lib/sacdiso -I../../src/lib/sacdiso -I../../src/lib/sacdiso/libdstdec -I../../src/lib/sacdiso/libdstdec/binding -I../../src/lib/sacdiso/libdstdec/decoder -Isrc/lib/dvdaiso -I../../src/lib/dvdaiso -I../../src/lib/dvdaiso/libmlpdec -I../../src/lib/dvdaiso/libmlpdec/libavutil -I../../src/lib/dvdaiso/libudf -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O2 -g -Wall -Wextra -Wvla -fvisibility=hidden -ffast-math -ftree-vectorize -fno-threadsafe-statics -fmerge-all-constants -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wwrite-strings -Wsign-compare -Wno-non-virtual-dtor -Wno-noexcept-type -ffunction-sections -fdata-sections -D_GNU_SOURCE -fPIC -MD -MQ 'src/util/ed6d25d@@util@sta/StringUtil.cxx.o' -MF 'src/util/ed6d25d@@util@sta/StringUtil.cxx.o.d' -o 'src/util/ed6d25d@@util@sta/StringUtil.cxx.o' -c ../../src/util/StringUtil.cxx
corrupted size vs. prev_size
during RTL pass: jump_after_combine
../../src/util/StringUtil.cxx: In function ‘bool StringArrayContainsCase(const char* const*, StringView)’:
../../src/util/StringUtil.cxx:53:1: internal compiler error: Aborted
   53 | }
      | ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.archlinux.org/> for instructions.
[15/693] Compiling C++ object 'src/util/ed6d25d@@util@sta/NumberParser.cxx.o'
FAILED: src/util/ed6d25d@@util@sta/NumberParser.cxx.o 
c++ -Isrc/util/ed6d25d@@util@sta -Isrc/util -I../../src/util -Isrc -I../../src -I. -I../.. -Isrc/lib/sacdiso -I../../src/lib/sacdiso -I../../src/lib/sacdiso/libdstdec -I../../src/lib/sacdiso/libdstdec/binding -I../../src/lib/sacdiso/libdstdec/decoder -Isrc/lib/dvdaiso -I../../src/lib/dvdaiso -I../../src/lib/dvdaiso/libmlpdec -I../../src/lib/dvdaiso/libmlpdec/libavutil -I../../src/lib/dvdaiso/libudf -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O2 -g -Wall -Wextra -Wvla -fvisibility=hidden -ffast-math -ftree-vectorize -fno-threadsafe-statics -fmerge-all-constants -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wwrite-strings -Wsign-compare -Wno-non-virtual-dtor -Wno-noexcept-type -ffunction-sections -fdata-sections -D_GNU_SOURCE -fPIC -MD -MQ 'src/util/ed6d25d@@util@sta/NumberParser.cxx.o' -MF 'src/util/ed6d25d@@util@sta/NumberParser.cxx.o.d' -o 'src/util/ed6d25d@@util@sta/NumberParser.cxx.o' -c ../../src/util/NumberParser.cxx
In file included from /usr/include/c++/10.1.0/algorithm:62,
                 from ../../src/util/NumberParser.cxx:34:
/usr/include/c++/10.1.0/bits/stl_algo.h:2263:5: error: ‘virtual’ outside class declaration
 2263 |     const _Tp& __val)
      |     ^~~~~
[16/693] Compiling C++ object 'src/util/ed6d25d@@util@sta/TruncateString.cxx.o'
ninja: build stopped: subcommand failed.
ninja -C output/release  15.70s user 2.11s system 323% cpu 5.497 total
1 roon@apl ~/Music/mpd-manisiutkin (git)-[master] %

**Comment by archphile** [comment]
This is not my code. It's just a backup of:

https://sourceforge.net/p/sacddecoder/mpd/MPD.git/ci/master/tree/

**Comment by speeedturtle** [comment]
sorry, I don't know it was a backup. by the way, could you tell me if archphile support x86 pc ?
